swipe:
  3:
    left:
      command: 'xdotool key Alt+Right'
    right:
      command: 'xdotool key Alt+Left'
    up:
      command: 'xdotool key Ctrl+Alt+Shift+D'
    down:
      command: 'xdotool key Ctrl+Alt+Shift+D'
  4:
    up:
      command: 'xdotool key super+m'
    down:
      command: 'xdotool key super+m'
    left:
      command: 'xdotool key Shift+Right'
    right:
      command: 'xdotool key Shift+Left'
pinch:
  in:
    command: 'xdotool key Ctrl+\='
    threshold: 0.1
  out:
     command: 'xdotool key Ctrl+\-'
     threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
